"""agregar seccion a producto

Revision ID: 052b4dd08480
Revises: fdc86b8dcf0d
Create Date: 2026-09-02 22:48:44.388269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '052b4dd08480'
down_revision: Union[str, Sequence[str], None] = 'fdc86b8dcf0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_producto', sa.Column('seccion', sa.String(length=20), nullable=False))
    op.create_check_constraint('ck_producto_seccion', 't_producto', "seccion IN ('HOMBRE', 'MUJER', 'UNISEX')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_producto_seccion', 't_producto', type_='check')
    op.drop_column('t_producto', 'seccion')
    # ### end Alembic commands ###
