"""vincular proveedor con usuario

Revision ID: 0c173d413ca6
Revises: 052b4dd08480
Create Date: 2026-09-02 23:56:27.528928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c173d413ca6'
down_revision: Union[str, Sequence[str], None] = '052b4dd08480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_proveedor', sa.Column('id_usuario', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_proveedor_id_usuario', 't_proveedor', ['id_usuario'])
    op.create_foreign_key('fk_proveedor_usuario', 't_proveedor', 't_usuario', ['id_usuario'], ['id_usuario'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_proveedor_usuario', 't_proveedor', type_='foreignkey')
    op.drop_constraint('uq_proveedor_id_usuario', 't_proveedor', type_='unique')
    op.drop_column('t_proveedor', 'id_usuario')
    # ### end Alembic commands ###
