"""crear tablas ciclo1

Revision ID: fdc86b8dcf0d
Revises: 
Create Date: 2026-09-02 22:27:58.628312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc86b8dcf0d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_categoria',
    sa.Column('id_categoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('t_ciudad',
    sa.Column('id_ciudad', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_ciudad'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('t_coleccion',
    sa.Column('id_coleccion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_coleccion')
    )
    op.create_table('t_color',
    sa.Column('id_color', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('codigo_hex', sa.String(length=7), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_color'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('t_proveedor',
    sa.Column('id_proveedor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('nit', sa.String(length=30), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_proveedor')
    )
    op.create_table('t_rol',
    sa.Column('id_rol', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('t_talla',
    sa.Column('id_talla', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_talla'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('t_temporada',
    sa.Column('id_temporada', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_temporada')
    )
    op.create_table('t_producto',
    sa.Column('id_producto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('id_temporada', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('precio >= 0'),
    sa.ForeignKeyConstraint(['id_categoria'], ['t_categoria.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_temporada'], ['t_temporada.id_temporada'], ),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_table('t_sucursal',
    sa.Column('id_sucursal', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_ciudad', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('hora_apertura', sa.Time(), nullable=True),
    sa.Column('hora_cierre', sa.Time(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_ciudad'], ['t_ciudad.id_ciudad'], ),
    sa.PrimaryKeyConstraint('id_sucursal')
    )
    op.create_table('t_usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['t_rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('t_cliente',
    sa.Column('id_cliente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('genero', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['t_usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_table('t_empleado',
    sa.Column('id_empleado', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('ci', sa.String(length=30), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['t_usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_empleado'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_table('t_imagen_producto',
    sa.Column('id_imagen_producto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('url_imagen', sa.Text(), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['t_producto.id_producto'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_imagen_producto')
    )
    op.create_table('t_producto_coleccion',
    sa.Column('id_producto_coleccion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_coleccion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_coleccion'], ['t_coleccion.id_coleccion'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['t_producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_producto_coleccion'),
    sa.UniqueConstraint('id_producto', 'id_coleccion')
    )
    op.create_table('t_producto_proveedor',
    sa.Column('id_producto_proveedor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('costo_referencia', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.CheckConstraint('costo_referencia IS NULL OR costo_referencia >= 0'),
    sa.ForeignKeyConstraint(['id_producto'], ['t_producto.id_producto'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['t_proveedor.id_proveedor'], ),
    sa.PrimaryKeyConstraint('id_producto_proveedor'),
    sa.UniqueConstraint('id_producto', 'id_proveedor')
    )
    op.create_table('t_variante_producto',
    sa.Column('id_variante_producto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_talla', sa.Integer(), nullable=False),
    sa.Column('id_color', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_color'], ['t_color.id_color'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['t_producto.id_producto'], ),
    sa.ForeignKeyConstraint(['id_talla'], ['t_talla.id_talla'], ),
    sa.PrimaryKeyConstraint('id_variante_producto'),
    sa.UniqueConstraint('id_producto', 'id_talla', 'id_color'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('t_empleado_sucursal',
    sa.Column('id_empleado_sucursal', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('id_sucursal', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_empleado'], ['t_empleado.id_empleado'], ),
    sa.ForeignKeyConstraint(['id_sucursal'], ['t_sucursal.id_sucursal'], ),
    sa.PrimaryKeyConstraint('id_empleado_sucursal'),
    sa.UniqueConstraint('id_empleado', 'id_sucursal')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_empleado_sucursal')
    op.drop_table('t_variante_producto')
    op.drop_table('t_producto_proveedor')
    op.drop_table('t_producto_coleccion')
    op.drop_table('t_imagen_producto')
    op.drop_table('t_empleado')
    op.drop_table('t_cliente')
    op.drop_table('t_usuario')
    op.drop_table('t_sucursal')
    op.drop_table('t_producto')
    op.drop_table('t_temporada')
    op.drop_table('t_talla')
    op.drop_table('t_rol')
    op.drop_table('t_proveedor')
    op.drop_table('t_color')
    op.drop_table('t_coleccion')
    op.drop_table('t_ciudad')
    op.drop_table('t_categoria')
    # ### end Alembic commands ###
